### ISSUE TITLE
Capitalisation of action package name

### ISSUE THREAD

**Issue by KieranMul16** [Stevedow99/dbt-cloud-cancel-running-ci-job-action#10]
Hey,

When going through your examples in the README I hit the following issue:

*This didn't work:*
```
uses: stevedow99/dbt-cloud-cancel-running-ci-job-action@v1.3
```

*This did work:*
```
uses: Stevedow99/dbt-cloud-cancel-running-ci-job-action@v1.3
```

I think this action is great and will be really helpful -- I just wanted to share in case others also hit this issue.

**Comment by Stevedow99** [comment]
ahh @KieranMul16 great call out, I will update it. Thank you for taking the time to post an issue!
