### ISSUE TITLE
KeyError: 'data' when searching for recent CI runs

### ISSUE THREAD

**Issue by ThomasMonnier** [Stevedow99/dbt-cloud-cancel-running-ci-job-action#2]
Hi,
I was very interested in your work, but I'm facing somehow an issue that I don't understand, and I would really appreciate if you could enlighten me on that.
I have always the same error for the step `Cancel another other CI runs that are running except the latest run` of the job, as you can see below:

<img width="1064" alt="Capture d’écran 2022-10-27 à 18 47 49" src="https://user-images.githubusercontent.com/101259769/198350731-c3021dbe-4775-4ee5-a63b-73656c4d3267.png">

I looked at your code, but I can't figure it out easily, thus I'm asking for your help to know if you've ever encountered this error.
Obviously, I can't retrieve correctly `recent_runs`, but why? I defined correctly the secrets in GitHub (DBT_CLOUD_TOKEN, DBT_ACCOUNT_ID, DBT_JOB_ID).
Thank you very much,

Regards,
Thomas Monnier

**Comment by Stevedow99** [comment]
Hi @ThomasMonnier ! 

Were you able to figure out the issue? If so, what was causing it? 

I admittedly need to do more stress testing on the code so it works for all scenarios and want to make sure i'm covering all bases. 

Thanks for taking the time to open an issue!

**Comment by ThomasMonnier** [comment]
Hi @Stevedow99 ! 

I was able to figure out the issue. In fact, I made a mistake when creating the secret DBT_CLOUD_TOKEN, I named it DBT_TOKEN. It was so stupid that I felt a little bit ashamed ahah

A big thanks to you and your awesome package that is really helpful !

**Comment by Stevedow99** [comment]
@ThomasMonnier Haha no worries, i'm always guilty of doing stuff like that.

Let me know if you run into any issues or anything else you'd like to see in the action!

**Comment by ThomasMonnier** [comment]
Just to inform you, I forked your project and will create a pull request in the next few days. To test if my modifications are working, I will release the action with my account, but I will delete it as soon as I'm sure that everything goes well. I won't steal your work or anything, it's not the purpose, but I just want to be sure that my modifications are good :)

I'll keep you updated, and once again, thanks a lot for your amazing work !

**Comment by Stevedow99** [comment]
Sounds good! Thanks Thomas!
